### ISSUE TITLE
Failing to populate the command, cloudConfig and units in the OSC status

### ISSUE THREAD

**Issue by vpnachev** [gardener/gardener-extension-os-ubuntu#39]
**How to categorize this issue?**

/area os
/kind bug
/priority 3
/os ubuntu

**What happened**:
Shoot creation is failing with 
```
Error while waiting for OperatingSystemConfig shoot--foo--bar/cloud-config-worker-1-a93d4-downloader to become ready: no cloud config information provided in status.
```

For some reason, the OSC status is not updated properly here https://github.com/gardener/gardener-extension-os-ubuntu/blob/168ece194e252c02bfaf7ecfe867ef7dedf44ac5/vendor/github.com/gardener/gardener/extensions/pkg/controller/operatingsystemconfig/reconciler.go#L146 even though the resource is successfully reconciled by the extension. There is no error also in the extension's logs.

**What you expected to happen**:
The osc.status.cloudConfig to be properly populated.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version (if relevant): master
- Extension version: 168ece194e252c02bfaf7ecfe867ef7dedf44ac5
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration: Observed on Alicloud and OpenStack, but most probably is not cloud specific.
- Others:

**Comment by BeckerMax** [comment]
Observed the same issue on GL when testing the gl-os-extension with [commit](https://github.com/gardener/gardener-extension-os-gardenlinux/commit/a5dd5e2c0c83aaed570fa52384719ba8b2ba85cd)
